### PR TITLE
Feature/controller tests

### PR DESCRIPTION
**Pull request by TheLuisAbarca**
1. Add Rspec-rails to the gemfile.
2. Execute command: 'rails generate rspec:install'.
3. Add 'rails-controller-testing' to Gemfile.
4. Add indications of how to implement routes for future references.
5. Add Request folder path for Post and Users tests.
6. Fix Rubocop Linters.

### CODE REVIEW

**Review by enaburekhan — CHANGES_REQUESTED** [review]
Hi TheLuisAbarca, 

Good job so far!

- [ ] Major highlights

- The PR summary and commit messages are very descriptive.
- The codebase is clean, easy to read and understand.
- Passed linters checks

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] In the getting started section of the readme. Kindly add how to test the app locally using `RSpec` testing framework

I had to add this comment here because tno commits were made to the readme in the PR.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Code review by **Eric Enaburekhan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TheLuisAbarca** [comment]
Hello @enaburekhan, thanks for your kind feedback! You are completely right, let me update the README file.

**Comment by TheLuisAbarca** [comment]
> Hi TheLuisAbarca,
> 
> Good job so far!
> 
>     * [ ]  Major highlights
> 
>     * The PR summary and commit messages are very descriptive.
> 
>     * The codebase is clean, easy to read and understand.
> 
>     * Passed linters checks
> 
> 
> However, there are some issues that you still need to work on to go to the next project but you are almost there!
> ## Required Changes recycle
> 
>     * [ ]  In the getting started section of the readme. Kindly add how to test the app locally using `RSpec` testing framework
> 
> 
> I had to add this comment here because tno commits were made to the readme in the PR.
> ## Optional suggestions
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!clapclapclap
> 
> Code review by **Eric Enaburekhan**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

The change is now implemented on the commit [5ac95d7](https://github.com/TheLuisAbarca/RoR_Blog-App/pull/2/commits/5ac95d7a27599df09e62e483aaf3d55f4ff06b54). Again, thanks for your feedback @enaburekhan :+1:

**Review by enaburekhan — APPROVED** [review]
Hi TheLuisAbarca, 

Great job on making the suggested changes.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Code review by **Eric Enaburekhan**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
